# Generated by Django 5.2.4 on 2025-07-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_sede_client_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
