# Generated by Django 5.2.4 on 2025-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Cedula', 'Cedula'), ('Cedula Extranjeria', 'Cedula Extranjeria')], default='Cedula', max_length=50),
        ),
    ]
