# Generated by Django 5.2.4 on 2025-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sede',
        ),
        migrations.AddField(
            model_name='sede',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='clients.client'),
        ),
    ]
