# Generated by Django 5.2.4 on 2025-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Funcional', 'Funcional'), ('En Mantenimiento', 'En Mantenimiento'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Funcional', max_length=20),
        ),
    ]
