# Generated by Django 5.2.4 on 2025-07-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-tipo', '-estado'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='observaciones',
        ),
    ]
