# Generated by Django 5.2.4 on 2025-07-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_completado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='materiales_utilizados',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tiempo_estimado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tiempo_real',
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
