# Generated by Django 5.2.4 on 2025-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_ordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteservicio',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Reporte de Servicio', 'verbose_name_plural': 'Reportes de Servicio'},
        ),
        migrations.RenameField(
            model_name='reporteservicio',
            old_name='fecha_creacion',
            new_name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='numero_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='reporteservicio',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='reporteservicio',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='reporteservicio',
            name='numero_reporte',
        ),
        migrations.RemoveField(
            model_name='reporteservicio',
            name='recomendaciones',
        ),
        migrations.RemoveField(
            model_name='reporteservicio',
            name='resumen_trabajo',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Generada', 'Generada'), ('Incompleta', 'Incompleta'), ('Completa', 'Completa')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Programado', 'Programado'), ('En Ejecucion', 'En Ejecucion'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Registrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Predictivo', 'Predictivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('Generada', 'Generada'), ('Asignada', 'Asignada'), ('En Curso', 'En Curso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Generada', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporteservicio',
            name='estado',
            field=models.CharField(choices=[('No Emitido', 'No Emitido'), ('Emitido', 'Emitido'), ('Revisado', 'Revisado'), ('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado')], default='borrador', max_length=20),
        ),
    ]
