# Generated by Django 5.2.4 on 2025-07-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_reporteservicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteservicio',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Reporte de Servicio', 'verbose_name_plural': 'Reportes de Servicio'},
        ),
        migrations.RemoveField(
            model_name='reporteservicio',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='reporteservicio',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
