# Generated by Django 5.2.4 on 2025-07-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ingeniero', 'Ingeniero'), ('Supervisor_Cliente', 'Supervisor Cliente'), ('Tecnico', 'Técnico')], default='tecnico', max_length=30),
        ),
    ]
