# Generated by Django 5.2.4 on 2025-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_primer_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
