# Generated by Django 5.2.4 on 2025-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ingeniero', 'Ingeniero'), ('Supervisor_Cliente', 'Supervisor Cliente')], default='tecnico', max_length=30),
        ),
    ]
