# Generated by Django 5.2.4 on 2025-07-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rol',
            new_name='role',
        ),
    ]
